language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.6"
  - "2.7"
install:
  - sudo apt-get update
  - pip install -r requirements.txt --use-mirrors
  - pip install .
  - pip install coverage
  - pip install coveralls

script:
  - coverage run --source=mbuild setup.py test

after_success:
  - coveralls
