language: c

sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

install:
  - source devtools/travis-ci/install.sh

script:
  - conda config --add channels omnia
  - conda config --add channels patrickfuller
  - conda update conda
  - conda update -y conda-build
  - conda build devtools/conda-recipe

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34

  global:
    # ANACONDA_TOKEN
    - secure: "K5o1SdlNrrnbtAyMdIvJodUeVolEd8sMenBw3y33cyZEcAfH1NBpn4Yd2bKyPmOly8Nu9fxB4NLgpWfL4QNE+c7T1GindidTtzzDeIk0laAkRRMNaGrHOe0dfffVTZrRQPVHkdmeEmPQvasCgKYerxUuYWZca8sueVLEb6MbY7E="
    # GITHUB
    - secure: "gtj9VfJQzQb4KL23+aRfimQgXBK88JHEqmN6zi+MCCLrjhnXs7+qWoAGi4kqwNeNd9fXSK5Wk+PfPHEPjP8MFyjEhWBL9LD9ct+59RVx8bf3pe2WOWktpf440XxwpLuDEWrV01Ly4FKRqYTOvtz7pYV5y/JgCyCP76MwkWhZvG4="

after_success:
  - source devtools/travis-ci/post_binstar.sh
  - source devtools/travis-ci/create_docs.sh

