language: generic

sudo: false

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=2.7 }
    - { os: linux, env: PYTHON_VERSION=3.4 }
    - { os: linux, env: PYTHON_VERSION=3.5 }
    - { os: osx, env: PYTHON_VERSION=3.5 }

env:
  global:
  - ENCRYPTION_LABEL: "898e0934cf65"
  - COMMIT_AUTHOR_EMAIL: "janos.sallai@vanderbilt.edu"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - source devtools/travis-ci/install.sh
  - conda config --add channels omnia
  - conda config --add channels janschulz
  - conda config --add channels bioconda
  - conda config --add channels glotzer

script:
  - conda build devtools/conda-recipe

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then source devtools/travis-ci/update_gh_pages.sh; fi
