language: c

install:
  - source devtools/travis-ci/install.sh

script:
  - conda config --add channels https://conda.binstar.org/omnia
  - conda build devtools/conda-recipe

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.3  CONDA_PY=33
    - python=3.4  CONDA_PY=34

  global:
    # BINSTAR
    - secure: "Rbt/6qSNB/6hvDKboKqo7iS1I+Zhye5u9k/RxNZCpaUQUiledjuzsBo+vppYskb7vHS+QRT+leDm7gUo/ZOv0DahLi4ScCIhvPSYTtWu+hKlp7TcI0woi5H7gCmGvP8bEYVPlHm3AT54xh7dzpfOca5eHpo8dVtvJhNTqbY8jPw="
    # GITHUB
    - secure: "XQ1fc/HXaQanzWq8Tn94RUPjqwjdImvq+Awfk3S0GqLGZnIpa/8rnXAr3HE/SmS8W+V1XBVM3LDXzwijP4tpPNMv7OU7DadKRx9pjaN4uj2d9r3DGp+thEalhnyrRMhA49aEi9BOgKwkd2Fiu8kwJGQiLeyFkfveXgEuJBASzp4="

after_success:
  - source devtools/travis-ci/after_sucess.sh

