package:
  name: mbuild-dev
  version: !!str 0.6.0.dev0

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - scipy
    - mdtraj
    - packmol 1.0.0=2
    - imolecule
    - oset
    - networkx
    - parmed

test:
  requires:
    - pytest
  commands:
    - py.test -v --pyargs mbuild

about:
  home: http://imodels.github.io/mbuild
  license: MIT
  summary: A hierarchical, component based molecule builder.
