package:
  name: mbuild
  version: !!str 0.5.0.dev0
  # version: "1.0"
  # the version is actually being set by the __conda_version__.txt file
  # http://conda.pydata.org/docs/build.html#post-build-version

build:
  noarch_python: True

requirements:
  build:
    - python

  run:
    - python
    - mdtraj
    - packmol
    - scipy
    - numpy
    - future
    - six

test:
    requires:
        - pytest
    commands:
        - py.test --pyargs mbuild

about:
  home: https://iModels.github.io/mbuild
  license: MIT
  summary: A hierarchical, component based molecule builder.